set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# all scripts is from: https://gist.github.com/dalbertom/3d9469b291eba10b56f38ecefe0c925d

bind-key -n C-s run-shell "bash ~/.config/tmux/scripts/SaveTmuxSession"
