set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# all scripts is from: https://gist.github.com/dalbertom/3d9469b291eba10b56f38ecefe0c925d

set-hook -g session-created 'run-shell "~/.config/tmux/scripts/SaveTmuxSession"'
set-hook -g session-renamed 'run-shell "~/.config/tmux/scripts/SaveTmuxSession"'
set-hook -g session-closed 'run-shell "~/.config/tmux/scripts/SaveTmuxSession"'
set-hook -g window-linked 'run-shell "~/.config/tmux/scripts/SaveTmuxSession"'
set-hook -g window-renamed 'run-shell "~/.config/tmux/scripts/SaveTmuxSession"'
set-hook -g window-unlinked 'run-shell "~/.config/tmux/scripts/SaveTmuxSession"'
set-hook -g window-layout-changed 'run-shell "~/.config/tmux/scripts/SaveTmuxSession"'
