[[manager.prepend_keymap]]
on   = [ "g", "h" ]
run  = "cd ~/workspace/github.com/zulkou/"
desc = "cd to /github.com/zulkou"

[[manager.prepend_keymap]]
on = [ "g", "d" ]
run = "cd ~/dotfiles"
desc = "cd to ~/dotfiles"

[[manager.prepend_keymap]]
on = [ "\\" ]
run = "shell nvim --block" 
desc = "run nvim"
